version: '3.8'

services:
  ragflow:
    image: infiniflow/ragflow:latest
    container_name: ragflow
    ports:
      - "9388:9380"  # RAGFlow default port
    environment:
      - MYSQL_PASSWORD=infiniflow
      - ELASTICSEARCH_PASSWORD=infiniflow
    volumes:
      - ragflow_data:/ragflow
      - ./ragflow_logs:/ragflow/logs
    depends_on:
      - ragflow-mysql
      - ragflow-elasticsearch
    restart: unless-stopped
    networks:
      - ragflow-network

  ragflow-mysql:
    image: mysql:8.0
    container_name: ragflow-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=infiniflow
      - MYSQL_DATABASE=ragflow
      - MYSQL_USER=ragflow
      - MYSQL_PASSWORD=infiniflow
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - ragflow-network

  ragflow-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ragflow-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - ragflow-network

volumes:
  ragflow_data:
  mysql_data:
  es_data:

networks:
  ragflow-network:
    driver: bridge
